package br.edu.safeplace.backend.domain.epi;

public enum ClassificacaoEPI {
    PROTECAO_CONTRA_QUEDAS,
    PROTECAO_DE_MEMBROS_INFERIORES,
    PROTECAO_DE_MEMBROS_SUPERIORES,
    PROTECAO_DE_TRONCO,
    PROTECAO_RESPIRATORIA,
    PROTECAO_AUDITIVA,
    PROTECAO_DE_OLHOS,
    PROTECAO_DE_FACE,
    PROTECAO_DE_CABECA
}
