import { test, expect } from '@playwright/test'

test('buttons keep the Figma geometry and block repeat activation while loading', async ({ page }) => {
  await page.goto('/design-system')
  const button = page.getByRole('button', { name: 'Simular espera' })
  await expect(button).toHaveCSS('height', '44px')
  await expect(button).toHaveCSS('background-color', 'rgb(23, 75, 63)')
  await button.hover()
  await expect(button).toHaveCSS('background-color', 'rgb(16, 47, 41)')
  await button.focus()
  await expect(button).toHaveCSS('outline-width', '2px')
  await button.click()
  await expect(button).toBeDisabled()
  await expect(button).toHaveAttribute('aria-busy', 'true')
  await page.keyboard.press('Enter')
  await expect(page.getByText('1 ativação. Durante a espera')).toBeVisible()
  await page.getByRole('button', { name: 'Finalizar espera' }).click()
  await expect(button).toBeEnabled()
  await button.click()
  await expect(page.getByText('2 ativações. Durante a espera')).toBeVisible()
})

test('fields expose labels, errors, read-only values and native selection', async ({ page }) => {
  await page.goto('/design-system#fields')
  const field = page.getByRole('textbox', { name: 'Setor vazio' })
  await field.fill('Expedição')
  await expect(field).toHaveValue('Expedição')
  await expect(field).toHaveAccessibleDescription('Informe o setor onde ocorreu o fato.')
  await expect(page.getByRole('textbox', { name: 'Setor com erro' })).toHaveAttribute('aria-invalid', 'true')
  await expect(page.getByRole('textbox', { name: 'Setor com erro' })).toHaveAccessibleDescription('Informe o setor para continuar.')
  await expect(page.getByRole('textbox', { name: 'Setor desabilitado' })).toBeDisabled()
  await expect(page.getByRole('textbox', { name: 'Setor em consulta' })).not.toBeEditable()
  await page.getByRole('combobox', { name: 'Selecionar setor', exact: true }).selectOption('Oficina de manutenção')
  await expect(page.getByRole('combobox', { name: 'Selecionar setor', exact: true })).toHaveValue('Oficina de manutenção')
})

test('checkboxes, radio groups and switches work with the keyboard', async ({ page }) => {
  await page.goto('/design-system#fields')
  const checkbox = page.getByRole('checkbox', { name: 'Selecionar EPI', exact: true })
  await checkbox.focus()
  await page.keyboard.press('Space')
  await expect(checkbox).toBeChecked()
  const group = page.getByRole('group', { name: 'Escolha única' })
  await group.getByRole('radio', { name: 'Incidente' }).focus()
  await page.keyboard.press('ArrowDown')
  await expect(group.getByRole('radio', { name: 'Acidente' })).toBeChecked()
  await expect(group.getByRole('radio', { name: 'Incidente' })).not.toBeChecked()
  const toggle = page.getByRole('switch', { name: 'Mostrar somente pendências' })
  await toggle.focus()
  await page.keyboard.press('Space')
  await expect(toggle).toBeChecked()
  await expect(page.getByRole('switch', { name: 'Alternância indisponível' })).toBeDisabled()
})

test('form validation preserves data, focuses the error and announces the simulated result', async ({ page }) => {
  await page.goto('/design-system#form-example')
  const sector = page.getByRole('combobox', { name: 'Setor (obrigatório)' })
  const description = page.getByRole('textbox', { name: 'Descrição dos fatos (obrigatório)' })
  const submit = page.getByRole('button', { name: 'Testar envio' })
  await description.fill('Caixa próxima à passagem.')
  await submit.click()
  await expect(sector).toBeFocused()
  await expect(sector).toHaveAttribute('aria-invalid', 'true')
  await expect(description).toHaveValue('Caixa próxima à passagem.')
  await sector.selectOption('loading')
  await page.getByLabel('Anexos', { exact: true }).setInputFiles({ name: 'observacao.txt', mimeType: 'text/plain', buffer: Buffer.from('Fictional attachment.') })
  await submit.click()
  await expect(submit).toBeDisabled()
  await expect(page.getByText('Demonstração concluída. Nenhum registro foi enviado.')).toBeVisible()
  await expect(submit).toBeEnabled()
  await expect(sector).not.toHaveAttribute('aria-invalid', 'true')
  await page.getByRole('button', { name: 'Limpar exemplo' }).click()
  await expect(description).toHaveValue('')
  await expect(sector).toHaveValue('')
})

test('confirmation contains focus, supports Escape and restores the opener', async ({ page }) => {
  await page.goto('/design-system#feedback')
  const opener = page.getByRole('button', { name: 'Testar confirmação de saída' })
  await opener.click()
  const dialog = page.getByRole('dialog', { name: 'Descartar alterações?' })
  await expect(dialog).toBeVisible()
  await expect(dialog.getByRole('button', { name: 'Continuar editando' })).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await expect(dialog.getByRole('button', { name: 'Descartar alterações', exact: true })).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(dialog.getByRole('button', { name: 'Continuar editando' })).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(dialog.getByRole('button', { name: 'Descartar alterações', exact: true })).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(dialog.getByRole('button', { name: 'Continuar editando' })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(dialog).not.toBeVisible()
  await expect(opener).toBeFocused()
  await opener.click()
  await dialog.getByRole('button', { name: 'Descartar alterações', exact: true }).click()
  await expect(page.getByText('Confirmação testada. Nenhum dado real foi alterado.')).toBeVisible()
  await page.getByRole('button', { name: 'Fechar aviso' }).click()
  await expect(page.getByText('Confirmação testada. Nenhum dado real foi alterado.')).not.toBeVisible()
})

test('tabs have one active panel and support arrow, Home and End keys', async ({ page }) => {
  await page.goto('/design-system#navigation')
  await page.getByRole('tab', { name: 'Dados do EPI' }).focus()
  await page.keyboard.press('ArrowRight')
  await expect(page.getByRole('tab', { name: 'Histórico' })).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByRole('tabpanel')).toHaveCount(1)
  await page.keyboard.press('End')
  await expect(page.getByRole('tab', { name: 'Empréstimos' })).toBeFocused()
  await page.keyboard.press('Home')
  await expect(page.getByRole('tab', { name: 'Dados do EPI' })).toBeFocused()
})

test('table selection and empty search recovery work', async ({ page }) => {
  await page.goto('/design-system#data')
  await page.getByRole('checkbox', { name: 'Selecionar Capacete de segurança' }).check()
  await expect(page.getByText('1 equipamento selecionado.')).toBeVisible()
  await page.getByRole('searchbox', { name: 'Buscar EPI', exact: true }).fill('inexistente')
  await expect(page.getByRole('heading', { name: 'Nenhum EPI encontrado' })).toBeVisible()
  await page.getByRole('button', { name: 'Limpar busca' }).click()
  await expect(page.getByRole('table', { name: 'EPIs de exemplo' })).toBeVisible()
  await page.getByRole('switch', { name: 'Somente disponíveis' }).check()
  await expect(page.getByRole('row')).toHaveCount(2)
})

test('reference filters combine and recover from no matches', async ({ page }) => {
  await page.goto('/design-system/examples/risk-areas')
  await page.getByRole('textbox', { name: 'Buscar setor' }).fill('area')
  await expect(page.getByRole('article')).toHaveCount(1)
  await page.getByRole('combobox', { name: 'Grau de perigo' }).selectOption('Médio')
  await expect(page.getByRole('heading', { name: 'Nenhuma área encontrada' })).toBeVisible()
  await page.getByRole('button', { name: 'Limpar filtros' }).click()
  await expect(page.getByRole('article')).toHaveCount(2)
  await page.getByRole('button', { name: 'Consultar área: Área de carga' }).click()
  await expect(page.getByRole('dialog', { name: 'Área de carga' })).toBeVisible()
  await page.getByRole('button', { name: 'Fechar consulta' }).click()
  await expect(page.getByRole('button', { name: 'Consultar área: Área de carga' })).toBeFocused()
})

for (const width of [360, 768, 1344]) {
  test(`reference and catalog fit ${width}px with local fonts and working navigation`, async ({ page }, testInfo) => {
    const errors: string[] = []
    page.on('pageerror', error => errors.push(error.message))
    page.on('response', response => { if (response.status() >= 400) errors.push(`${response.status()} ${response.url()}`) })
    await page.setViewportSize({ width, height: 960 })
    await page.goto('/design-system/examples/risk-areas')
    await page.evaluate(() => document.fonts.ready)
    await expect(page.getByRole('heading', { name: 'Áreas de risco', exact: true })).toHaveCSS('font-family', 'Manrope, sans-serif')
    const geometry = await page.getByRole('article').evaluateAll(cards => cards.map(card => ({ x: card.getBoundingClientRect().x, width: card.getBoundingClientRect().width, height: card.getBoundingClientRect().height })))
    expect(geometry[0].width).toBe(width === 1344 ? 520 : width === 768 ? 348 : 328)
    expect(geometry[0].height).toBeGreaterThanOrEqual(336)
    if (width === 360) expect(geometry[0].x).toBe(geometry[1].x)
    else expect(geometry[0].x).toBeLessThan(geometry[1].x)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    await page.screenshot({ path: testInfo.outputPath(`risk-areas-${width}.png`), fullPage: true })
    if (width < 1200) {
      const menu = page.getByRole('button', { name: 'Menu', exact: true })
      await menu.click()
      await expect(page.getByRole('dialog', { name: 'Navegação' })).toBeVisible()
      await page.keyboard.press('Escape')
      await expect(menu).toBeFocused()
      await menu.click()
      await page.setViewportSize({ width: 1344, height: 960 })
      await expect(page.getByRole('dialog', { name: 'Navegação' })).not.toBeVisible()
      await page.setViewportSize({ width, height: 960 })
    }
    await page.goto('/design-system')
    await page.evaluate(() => document.fonts.ready)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    await page.screenshot({ path: testInfo.outputPath(`catalog-${width}.png`), fullPage: true })
    expect(errors).toEqual([])
  })
}
